### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by DaveChild** [CloudManaged/oauth2-freeagent#6]
Hi. I'd like to use this, but the league/oauth2-client dependency conflicts with another oauth2 provider I'm using. Does this work with oauth2-client above 0.7? If so, can you update the dependencies please.

**Comment by designtwelve** [comment]
I'm trying to use this now, but it seems that league/oauth2-client version is way past 0.7 - it's at 2.3 at the time of writing.

Any change of updating the dependency so that we can make use of the new league/oauth2-client features within oauth2-freeagent ?

**Comment by designtwelve** [comment]
Thanks @dcorking - I think you're right.

I integrated with FreeAgent's API a couple of years ago, and now that I'm revisiting, I'm trying to find any packages that will save me reinventing the wheel.

**Comment by dcorking** [comment]
OK, thanks, I'll close this issue. I also discovered a fork of this project that might interest you. I haven't tried it, but it appears to be built against https://github.com/nathanbriggs/thephpleague/oauth2-client v2.0 : 

**https://github.com/nathanbriggs/oauth2-freeagent**

**Comment by dcorking** [comment]
@zot24 do you think thephpleague should still link to CloudManaged's code from [thirdparty.md](https://github.com/thephpleague/oauth2-client/blob/master/docs/providers/thirdparty.md) ?

**Comment by designtwelve** [comment]
$client = new OAuth2\Client(FREEAGENT_CLIENT_ID, FREEAGENT_CLIENT_SECRET);

@dcorking is this something you tried? Or were you guessing at the syntax?

**Comment by dcorking** [comment]
@designtwelve it is a snippet from some code I just saw running - but is not the most recent version of the client: I'd recommend referring to thephpleague's docs to do it right.

**Comment by designtwelve** [comment]
Cool - thanks @dcorking

**Comment by zot24** [comment]
I would personally mark it as **deprecated** or **unmaintained** so people won't be expecting it to work 😄 

It's a really old repo and I might then just leave it in the [thirdparty.md](https://github.com/thephpleague/oauth2-client/blob/master/docs/providers/thirdparty.md) maybe someday someone it's fancy to fork it and fix it for good.

There is definitely some people using it https://packagist.org/packages/cloudmanaged/oauth2-freeagent/stats
